name: fchatapi
description: "fchatapi"
version: 0.0.2
homepage:

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2
  crypto: ^3.0.1     #各种加密，签名综合组件
  flutter_screenutil: ^5.8.1
  chewie: 1.7.0
  http_client: ^1.5.2
  http_parser: ^4.0.1
  dio: ^5.4.0
  intl: ^0.19.0
  url_launcher: ^6.1.11
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/img/

  plugin:
    platforms:
      web:
        pluginClass: FchatapiWeb
        fileName: fchatapi_web.dart

